spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysql995.umbler.com:41890/trabalho-final-j
    username: lucashdp
    password: LbRLPp9Q7rkN7KG
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/stockmarket_prod
    username: springjpa_prod_user
    password: root
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
